# https://github.com/antlr/antlr4/blob/master/doc/getting-started.md
FROM openjdk:11

RUN cd /usr/local/lib && curl -O https://www.antlr.org/download/antlr-4.9-complete.jar

ENV CLASSPATH=".:/usr/local/lib/antlr-4.9-complete.jar:$CLASSPATH"
ENTRYPOINT ["java", "-Xmx500M", "-cp", "/usr/local/lib/antlr-4.9-complete.jar:$CLASSPATH", "org.antlr.v4.Tool"]
